In [1]:
from textblob import TextBlob
import pandas as pd
import json

In [2]:
def getSentimentPolarity(x):
    testimonial=TextBlob(x['text'])
    s=testimonial.sentiment.polarity
    return s
def getSentimentSubjectivity(x):
    testimonial=TextBlob(x['text'])
    s=testimonial.sentiment.subjectivity
    return s
def cleanText(x):
    import re
    str1=x['text']
    str2=re.split('RT @\w+: ',str1)
    if(len(str2))==2:
        return str2[1]
    else:
        return str2[0]

In [28]:
inname=str("Tesla/Tesla-2020-3-18")
infile=open(inname+".json", encoding='utf-8')
data = []
for lines in infile:
    try:
        df0=json.loads(lines)
        data.append(df0)
    except:
        continue
infile.close()
df = pd.DataFrame(data)
print(df)

                                                   text        from_user  \
0     RT @passthebeano: Musk will never be able to w...        maloftis1
1     RT @thelazygoan: So I made this @Tesla Cybertr...    thelandofgold
2     Yo @elonmusk, wanna send me to a different pla...     Justinaday77
3     The company operated its California factory no...  JessicaCryptoML
4     RT @undervalued: Stocks now from various secto...      tom_bibiyan
...                                                 ...              ...
1911  #corporateaccountability #COVID19 #COVID19USA@...         piehead9
1912  RT @vincent13031925: Tesla Best Prepared To Su...     rocobasilisk
1913  RT @vincent13031925: Tesla Will Be A Trillions...          getjeda
1914  RT @vincent13031925: Tesla Will Be A Trillions...           aryou7
1915  RT @vincent13031925: Tesla Best Prepared To Su...           aryou7

             from_user_id   geo                   id iso_language_code  \
0     1017864078323277824  None  1240427681625387012                en
1     1177004865844850688  None  1240427254343237632                en
2      807791127621353473  None  1240427222885748737                en
3     1143596939549663233  None  1240426819725209600                en
4                37230379  None  1240426340592959488                en
...                   ...   ...                  ...               ...
1911  1106585422510112768  None  1240065961245454337                en
1912   995458317634830336  None  1240065720429318144                en
1913   956834823557058560  None  1240065489256120320                en
1914           1596028178  None  1240065456981127169                en
1915           1596028178  None  1240065394028826626                en

         from_user_id_str           created_at               source  \
0     1017864078323277824  2020-03-18 23:59:39      Twitter Web App
1     1177004865844850688  2020-03-18 23:57:58  Twitter for Android
2      807791127621353473  2020-03-18 23:57:50  Twitter for Android
3     1143596939549663233  2020-03-18 23:56:14             Cloohawk
4                37230379  2020-03-18 23:54:20   Twitter for iPhone
...                   ...                  ...                  ...
1911  1106585422510112768  2020-03-18 00:02:19     Twitter for iPad
1912   995458317634830336  2020-03-18 00:01:21   Twitter for iPhone
1913   956834823557058560  2020-03-18 00:00:26      Twitter Web App
1914           1596028178  2020-03-18 00:00:18      Twitter Web App
1915           1596028178  2020-03-18 00:00:03      Twitter Web App

                   id_str                          from_user_name  \
0     1240427681625387012                          michael loftis
1     1240427254343237632                            LAND OF GOLD
2     1240427222885748737                             Justin Aday
3     1240426819725209600                          Jessica Crypto
4     1240426340592959488                             Tom Bibiyan
...                   ...                                     ...
1911  1240065961245454337  Professor Piehead (wearing Elonâ€™s Hat)
1912  1240065720429318144                            rocobasilisk
1913  1240065489256120320                           Jeda Products
1914  1240065456981127169                            TESLA Tweets
1915  1240065394028826626                            TESLA Tweets

                       metadata
0     {'result_type': 'recent'}
1     {'result_type': 'recent'}
2     {'result_type': 'recent'}
3     {'result_type': 'recent'}
4     {'result_type': 'recent'}
...                         ...
1911  {'result_type': 'recent'}
1912  {'result_type': 'recent'}
1913  {'result_type': 'recent'}
1914  {'result_type': 'recent'}
1915  {'result_type': 'recent'}

[1916 rows x 12 columns]

In [29]:
filename=inname
#df=pd.read_json(filename+".json", lines=True, encoding='utf-8')
df=df[['created_at','text']]
df['Polarity']=0
df['Subjectivity']=0
df['text']=df.apply(cleanText, axis=1)
df['Polarity']=df.apply(getSentimentPolarity, axis=1)
df['Subjectivity']=df.apply(getSentimentSubjectivity, axis=1)
df['Aggregate Score']=df['Polarity']*0.5+df['Subjectivity']*0.5
df.to_csv(filename+".csv")
print(f"Polarity:        {df['Polarity'].mean()}")
print(f"Subjectivity:    {df['Subjectivity'].mean()}")
print(f"Aggregate Score: {df['Aggregate Score'].mean()}")


df

Polarity:        0.15989146189410414
Subjectivity:    0.3281426532467764
Aggregate Score: 0.24401705757044023

,created_at,text,Polarity,Subjectivity,Aggregate Score
0,2020-03-18 23:59:39,Musk will never be able to wash the blood from...,0.128571,0.586905,0.357738
1,2020-03-18 23:57:58,So I made this @Tesla Cybertruck illustration....,0.150000,0.400000,0.275000
2,2020-03-18 23:57:50,"Yo @elonmusk, wanna send me to a different pla...",0.000000,0.600000,0.300000
3,2020-03-18 23:56:14,The company operated its California factory no...,0.150000,0.650000,0.400000
4,2020-03-18 23:54:20,Stocks now from various sectors:* Carnival #Cr...,0.000000,0.250000,0.125000
...,...,...,...,...,...
1911,2020-03-18 00:02:19,#corporateaccountability #COVID19 #COVID19USA@...,-0.800000,0.900000,0.050000
1912,2020-03-18 00:01:21,Tesla Best Prepared To Survive A Global Recess...,0.500000,0.150000,0.325000
1913,2020-03-18 00:00:26,Tesla Will Be A Trillions-Dollars Market Cap C...,-0.025000,0.350000,0.162500
1914,2020-03-18 00:00:18,Tesla Will Be A Trillions-Dollars Market Cap C...,-0.025000,0.350000,0.162500
1915,2020-03-18 00:00:03,Tesla Best Prepared To Survive A Global Recess...,0.500000,0.150000,0.325000